// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { ReactNode } from "react";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ChatbotPlaceholder from "./components/ChatbotPlaceholder";

export const metadata = {
  title: "Centro de Estudios Lerdo Contemporáneo",
  description: "Institución educativa — Kínder a Licenciatura",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        {/* Main content area */}
        <main className="pt-20">
          {children}
        </main>

        {/* Footer */}
        <Footer />

        {/* Chatbot placeholder (flotante, visible en todas las páginas) */}
        <ChatbotPlaceholder />
      </body>
    </html>
  );
}
